language: r
cache: packages

after_success:
  - "git config user.email 'travis-ci@example.com'"
  - "git config user.name 'Travis CI'"
  - "git remote -v"
  - "git fetch --unshallow -v"
  - "cp output/page.html index.html"
  - "git add index.html"
  - "git stash"
  - "git checkout gh-pages"
  - "git stash pop"
  - "git status"
  - "ls -l"

deploy:
  provider: releases
  api_key:
    secure: Yhu8YgX9lLBqQEvc3wdJ9gowNORg5hqWZ3/G9V+ak9OQR4kc2zbvj7MJUqGMG7wCbtsfg3kb5sot1D5PxoeSmCD/N4hRRLywgvd6J+0GvsATZZ4ZpVfMSsc3rbCW98rJUCaYbKY5PQTYhRkgKZ0oMQA3jjiRasXghEnupZ4g0veenWsyZho4UbKHeyKNZpUhcRGcVKk75o5jR5AJ2g1CJplhrmmNOfyg+rySFBOdxWo71VlLg6lU9hpPeaY9fNgcEa5Xf73qVkPxX/zdP8yR8OHvGC1/bqwjgZjrISkra68QM6MlmnXAS1Mxkt6XIsjVrvh8YZLD6SEBibiqlEWOymj+bpp+oobVxBQs776uT09HcheTt3C7853yDCJnhrEQjOSEZzX3i7Vt9qxjaaj4l+plQ4DSIOqmphw+C2/7+AKm6WJIUNyhWGKJuPaAlORae0YjRPcHpaYgnt5igLtI5o4Tf6gkU7LwGNDfAaD0H12QgnqEjcMoEB6kb3wzmsIDmyT8dCxMHH3oU8/rn5u88vnujUHSWpTuFNjMTv6mpMP9K/Ma8tgvJx5gkaOqj4m2/iFDI1dAMiRxT7rh78q7OHW3S50XtKL2IkRcHr+H0hBflIwR0/Ycn+C9RIrTCKw+pgUZBds4OaRbVKMdjRPVxdFod4iLAv+ak2ZTpa4Et4Q=
  file: output/page.html
  skip_cleanup: true
  overwrite: true
  on:
    tags: true
    repo: Joengenduvel/workflow-test
    all_branches: true
